apiVersion: v1
kind: PersistentVolume
metadata:
  name: code-web-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: code-web-storage
  local:
    path: /mnt/disk/vol
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - "k8s-node04"
