apiVersion: v1
kind: Pod
metadata:
  name: edu-cms
  labels:
    name: edu-cms
spec:
  containers:
  - name: edu-cms
    image: nginx:alpine
    ports:
      - containerPort: 80
        name: edu-cms
    volumeMounts:
      - name: code-web-storage
        subPath: edu-cms
        mountPath: /usr/share/nginx/html
  volumes:
    - name: code-web-storage
      persistentVolumeClaim:
        claimName: code-web-pvc
