apiVersion: v1
kind: Service
metadata:
  name: nexus-service
spec:
  ports:
  - port: 80
    targetPort: 8081
    protocol: TCP
    name: http
    nodePort: 30881
  - port: 8083
    targetPort: 8083
    nodePort: 30883
    protocol: TCP
    name: docker
  selector:
    app: nexus

  type: LoadBalancer
  externalIPs:
  - 192.168.10.220
