kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: glusterfs
provisioner: kubernetes.io/glusterfs
allowVolumeExpansion: true
parameters:
  resturl: "http://192.168.10.247:8080"
  #heketi-cli cluster list
  clusterId: "4b383fcf2db8020d1139722fddd2769d"
  restauthenabled: "true"
  restuser: "admin"
  secretName: "heketi-secret"
  secretNamespace: "default"
  volumetype: "replicate:2"
  volumenameprefix: "keepwalking"
